GET localhost:3001/authors

####

POST localhost:3001/authors/create HTTP/1.1

Content-Type: application/json

{
  "nome":"NomeProva",
  "cognome":"CognomeProva",
  "email":"nomeCognome@prova.com",
  "dataDiNascita":"18-5-2015",
  "avatar":"https://picsum.photos/200/300"
}