const mongoose = require('mongoose');
const newUserSchema = new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    surname:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    dateOfBirth:{
        type:Date,
        required:true
    },
    avatar:{
        type:String,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    post:{
        type:String,
        required:true
    }
})